apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker-demo
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: worker
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gs-key
      - name: plynx-config-volume
        configMap:
          name: plynx-config
      containers:
      - image: plynxteam/demo-nlp:0.0.3
        resources:
          requests:
            memory: "2048Mi"
        name: worker
        command:
          - plynx
          - worker
          - "-vvvv"
          - "--storage-scheme"
          - $(STORAGE_SCHEME)
          - "--storage-prefix"
          - $(STORAGE_PREFIX)
          - "--db-host"
          - mongo
          - "-e"
          - "demo-python-node-operation"
          - "-e"
          - "demo-dag-workflow"
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: plynx-config-volume
          mountPath: /etc/plynx-config
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: STORAGE_SCHEME
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: storage-scheme
        - name: STORAGE_PREFIX
          valueFrom:
            configMapKeyRef:
              name: storage-config
              key: storage-prefix
        - name: PLYNX_CONFIG_PATH
          value: /etc/plynx-config/config.yaml
      restartPolicy: Always
